import Providers from "./Providers";
import Header from "./components/Header/Header";
import Navbar from "./components/Navbar/Navbar";
import SearchBox from "./components/SearchBox";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDb Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {" "}
          {/* Even the Providers is client side,Header and children are still server side components::Kudos to Next.js 13 */}
          <Header />
          <Navbar />
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  );
}
